howtorubik/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'', include('rubikPost.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rubikPost/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.post_list, name="post_list"),
	url(r'^(?P<pk>\d+)/(?P<post_slug>[\w\d-]+)/$', views.post_detail, name="post_detail"),
	url(r'^tag/(?P<tag_slug>[\w\d-]+)/$', views.post_by_tag, name="post_by_tag"),
	url(r'^basic-3x3-cubing/', views.basicCubing, name="basicCubing"),
	url(r'^advanced-3x3-cubing/', views.advancedCubing, name="advancedCubing"),
	url(r'^basic-3x3-videos/', views.basicVideos, name="basicVideos"),
	url(r'^advanced-3x3-videos/', views.advancedVideos, name="advancedVideos"),
	url(r'^about/$', views.about, name="about"),
	url(r'contact/$', views.contact, name="contact")
]

rubikPost/models.py
from django.db import models
from django.core.urlresolvers import reverse
from ckeditor.fields import RichTextField

from django.utils.text import slugify

# Signals. Does a task Before saving something and after saving (Pre_save & Post_save)
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator


# Create your models here.
class Author(models.Model):
	name 			=	models.CharField(max_length=100, unique=True)
	email			=	models.EmailField(unique=True)
	active			=	models.BooleanField(default=False)
	created_on 		=	models.DateTimeField(auto_now_add=True)
	last_logged_in	=	models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name


class Category(models.Model):
	name 	=	models.CharField(max_length=100, unique=True)
	slug 	=	models.SlugField(max_length=100, unique=True)
	author 	=	models.ForeignKey(Author)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('post_by_category', args=[self.slug])

class Tag(models.Model):
	name 	=	models.CharField(max_length=100, unique=True)
	slug 	=	models.SlugField(max_length=100, unique=True)
	author 	=	models.ForeignKey(Author)


	def __str__(self):
		return self.name

	def get_absolute_urL(self):
		return reverse('post_by_tag', args=[self.slug])


class Post(models.Model):
	title 		=	models.CharField(max_length=150)
	slug 		=	models.SlugField(unique=True, help_text="Slug will be generated automatically.")
	content 	=	RichTextField()
	pub_date	=	models.DateTimeField(auto_now_add=True)
	updated_on	=	models.DateTimeField(auto_now=True)
	author 		=	models.ForeignKey(Author)
	category 	=	models.ForeignKey(Category)
	tags 		=	models.ManyToManyField(Tag)

	def get_absolute_url(self):
		return reverse('post_detail', args=[self.id, self.slug])

	def __str__(self):
		return self.title

	# overriding the Model's save() method to create 'slug' when Saved/Updated
	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)

class Contact(models.Model):
	name = models.CharField(max_length=200, help_text="Name of the sender")
	email = models.EmailField(max_length=200)
	subject = models.CharField(max_length=200)
	message = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Contact"

	def __str__(self):
		return self.name + "-" + self.email		

rubikPost/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = '__all__'

rubikPost/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from .models import Author, Tag, Category, Post
from django.contrib import messages # for Flash Messages
from .forms import ContactForm
from django.core.mail import mail_admins # Feedback form sending Emails



# Create your views here.

def post_list(request):
	'''Shows List of posts in Database'''
	posts = Post.objects.all()
	tags = Tag.objects.all()
	return render(request, 'rubikPost/post_list.html', {'posts':posts, 'tags': tags})

def post_detail(request, pk, post_slug):
	'''Shows the particular post'''
	#post = Post.objects.get(pk=pk)
	post = get_object_or_404(Post, pk=pk)
	tags = Tag.objects.all()
	return render(request, 'rubikPost/post_detail.html', {'post': post, 'tags':tags,})

def post_by_tag(request, tag_slug):
	''' Shows the post by tags '''
	tag = get_object_or_404(Tag, slug=tag_slug)
	tags= Tag.objects.all()
	posts = get_list_or_404(Post, tags=tag)
	context = {
		'tag': tag,
		'tags':tags,
		'posts': posts
	}
	return render(request, 'rubikPost/post_by_tag.html', context)

def basicCubing(request):
	posts = Post.objects.filter(category__name__icontains="basic").order_by("id")
	tags = Tag.objects.all()
	return render(request, 'rubikPost/basic_three.html', {'posts':posts, 'tags':tags,})

def advancedCubing(request):
	posts = Post.objects.filter(category__name__icontains="advance")
	tags = Tag.objects.all()
	return render(request, 'rubikPost/advance_three.html', {'posts':posts, 'tags':tags,})

def basicVideos(request):
	'''shows list of video tutorials'''
	tags = Tag.objects.all()
	return render(request, 'rubikPost/basic_videos.html', {'tags':tags})

def advancedVideos(request):
	'''shows list of video tutorials'''
	tags = Tag.objects.all()
	return render(request, 'rubikPost/advanced_videos.html', {'tags':tags})


def about(request):
	''' Shows about me '''
	return render(request, 'rubikPost/about.html')

# sidebox
def sidebox(request):
	tags = Tag.objects.all()
	return render(request, 'base.html', {'tags':tags})



# Feedback form view
def contact(request):
	if request.method == "POST":
		f = ContactForm(request.POST)

		if f.is_valid():
			name = f.cleaned_data['name']
			sender = f.cleaned_data['email']
			subject = "You have new Feedback from {}:{}".format(name, sender)
			message = "Subject: {}\n\nMessage: {}".format(f.cleaned_data['subject'], f.cleaned_data['message'])
			mail_admins(subject, message)

			f.save()
			messages.add_message(request, messages.INFO, "Feedback Submitted")
			return redirect('contact')
	else:
		f = ContactForm()
	return render(request, 'rubikPost/contact.html', {'form':f,})

rubikPost/templates/rubikPost/about.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}HowToRubiks{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
  	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'rubikPost/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'rubikPost/css/customStyles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'rubikPost/css/styles.css' %}">
	<script src="{% static 'rubikPost/js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'rubikPost/js/bootstrap.min.js' %}"></script>
</head>
<body>
	<div class="container-fluid mainDiv">
		{% include 'snippets/nav.html' %}

		<div class="container aboutContainer">
			<div class="row">
					<h1 class="page-header">About Me</h1>
					<div class="col-md-3 imgDiv">
						
						<img src="{% static 'rubikPost/img/sashi.jpg' %}" height="200px" width="180px" class="img-thumbnail">
					</div>
					<div class="col-md-9">
						<p>I am <b>Sashikanth</b> completed my <i>BSc</i> in <i>"Computers Science"</i> and I was always passionate about the Technology and Computers that are rapidly changing the way we live.</p>

						<p>With that passion, I started learning how to code in my college days. I learned that programming is the way people at Big technology companies making impact on world by making great tools and products for people to use.</p>

						<p>I started with simple <i><u>HTML, CSS</u></i> and later got to know that these are not enough to make something great. <br>So, I was ready to make my hands dirty by starting with real <b>Programming and business logic</b>. I started with <i><u>JavaScript</u></i> and now I am using <i><b><u>PYTHON / DJANGO</u></b></i> as my Backend Programming Language.
						</p>

						<p>I used <b>Python/Django, Bootstrap </b> to build this simple blogging site.</p>
					</div>
			</div>

			<div class="row followDiv">
				<div class="col-md-8">
					<h4>Follow me on:</h4>
					<div class="aboutFollow">
						
						<a href="https://www.github.com/satyasashi" target="_blank"><img src="{% static 'rubikPost/img/github.png' %}" height="50px" width="50px" style="margin-right: 5px;"></a>

						<a href="https://www.linkedin.com/in/sashi-kanth-635224b9/" target="_blank"><img src="{% static 'rubikPost/img/linkedin.png' %}" height="50px" width="50px"></a>


					</div>
				</div>
			</div>
		</div>
	</div>

	{% include "snippets/footer.html" %}

</body>
</html>

rubikPost/templates/rubikPost/advance_three.html
{% extends "base.html" %}

{% block title %}
	Basic 3x3 - {{block.super}}
{% endblock %}

{% block banner %}

{% endblock %}

{% block content %}
	<h1 class="page-header" style="text-align: center;">Advance 3x3 Cubing</h1>
		<div class="homePageContent">
			<!-- POST TITLE -->
			<div class="comingSoon">
				<h3>Oops! This page is still under construction...</h3>
			</div>

		</div>
{% endblock %}

{% block tags %}
	{% for tag in tags %}
		<span class="glyphicon glyphicon-tags">{{tag.name}}</span>
	{% endfor %}
{% endblock %}

rubikPost/templates/rubikPost/advanced_videos.html
{% extends "base.html" %}

{% block banner %}

{% endblock %}

{% block content %}
	<div class="homePageContent">
		<!-- POST TITLE -->
		<div class="row">
			<div class="col-md-9">
				
				<h1 class="page-header">Advanced Videos</h1>
				<div class="comingSoon">
				<h3>Oops! This page is still under construction...</h3>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block tags %}
	{% for tag in tags %}
		<span class="glyphicon glyphicon-tags">{{tag.name}}</span>
	{% endfor %}
{% endblock %}

rubikPost/templates/rubikPost/basic_three.html
{% extends "base.html" %}

{% block title %}
	Basic 3x3 - {{block.super}}
{% endblock %}

{% block banner %}

{% endblock %}

{% block content %}
	<h1 class="page-header" style="text-align: center;">Basic 3x3 Cubing</h1>
	{% for post in posts %}
		<div class="homePageContent">
			<!-- POST TITLE -->
			<h1>
				<a href="{{post.get_absolute_url}}">{{post.title|capfirst}}</a>
			</h1>

	<!-- TIME AND PUBLISH -->
		<i class="bg-info timestamp">
		<span class="glyphicon glyphicon-time"></span> Published:
		<b>{{post.pub_date}}</b>, By: <span class="glyphicon glyphicon-user"></span> <b>{{post.author.name|capfirst}}</b></i>

		<p>{{post.content|safe|truncatewords_html:50}}</p>

		{% if post %}
			<a class="btn btn-primary" href="{{post.get_absolute_url}}">Read More</a>
		{% endif %}


		</div>
		<br /><hr />
	{% endfor %}
{% endblock %}

{% block tags %}
	{% for tag in tags %}
		<span class="glyphicon glyphicon-tags">{{tag.name}}</span>
	{% endfor %}
{% endblock %}

rubikPost/templates/rubikPost/basic_videos.html
{% extends "base.html" %}

{% block banner %}

{% endblock %}

{% block content %}
	<div class="homePageContent">
		<!-- POST TITLE -->
		<div class="row">
			<div class="col-md-9">
				<h1 class="page-header">Basic 3x3 Videos</h1>

				<h3>First Layer - CROSS</h3>
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/KwiUwSv1W3s" allowfullscreen></iframe>
				</div>

				<h3>First Layer - Corners</h3>				
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/gI2L25Fll-k" allowfullscreen></iframe>
				</div>

				<h3>Second Layer - Edges</h3>
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/PN1MsYf94MU" allowfullscreen></iframe>
				</div>

				<h3>OLL</h3>
				<p>Orientation of Last Layer</p>
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/z5Xpde2Ygrg" allowfullscreen></iframe>
				</div>


				<h3>PLL</h3>
				<p>Permutation of Last Layer</p>
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/R1yRQln8BpA" allowfullscreen></iframe>
				</div>

			</div>
		</div>
	</div>
{% endblock %}

{% block tags %}
	{% for tag in tags %}
		<span class="glyphicon glyphicon-tags">{{tag.name}}</span>
	{% endfor %}
{% endblock %}

rubikPost/templates/rubikPost/contact.html
{% extends "base.html" %}

{% block title %}
	Contact - {{block.super}}
{% endblock %}

{% block banner %}

{% endblock %}


{% block content %}
	<div class="homePageContent">
		<p><<< <a href="#" onclick="goback()">Go Back</a></p>
			<h1 class="page-header">Submit Feedback</h1>
			{# If any field errors exist, show them in this common place. #}

			{{ form.non_field_errors }}
			
			{% if messages %}
			{% for msg in messages %}
				<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Success!</strong> Your Valuable Feedback Sent.
				</div>
			{% endfor %}
			{% endif %}
			
		<form action="" method="post">
			{% csrf_token %}
			<div class="form-group">
			<label for="id_name">Your Name</label>
			{{ form.name.errors }}
			{% if form.name.value %}
				<input class="form-control" name="name" type="text" id="id_name" placeholder="Enter your name" value="{{form.name.value}}" required="required">
			{% else %}
				<input class="form-control" type="text" name="name" id="id_name" placeholder="Enter your name" required="required">
			{% endif %}
			</div>

			<div class="form-group">
			<label for="id_email">Email address</label>
			{{ form.email.errors }}
			<input type="email" name="email" class="form-control" id="id_email" aria-describedby="emailHelp" placeholder="Enter your email" required="required">
			<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
			</div>

			<div class="form-group">
			<label for="id_subject">Subject</label>
			{{ form.subject.errors }}
			<input type="text" name="subject" class="form-control" id="id_subject" placeholder="Subject to message" required="required">
			</div>
			
			<div class="form-group">
			<label for="id_message">Message</label>
			{{ form.message.errors }}
			<textarea class="form-control" name="message" id="id_message" required="required" rows="3"></textarea>
			</div>

			<input type="submit" value="Submit" class="btn btn-primary">
		</form>
	</div>
{% endblock %}

rubikPost/templates/rubikPost/post_by_tag.html
{% extends "base.html" %}

{% block title %}
	{{block.super}}
{% endblock %}

{% block banner %}
{% endblock %}

{% block content %}
	<div class="homePageContent">
		<p><<< <a href="#" onclick="goback()">Go Back</a></p>


		<h1 class="page-header">Posts having Tags: {{tag.name}}</h1>

		{% if posts %}
			{% for post in posts %}
			<h1>
				<a href="{{post.get_absolute_url}}">{{post.title|capfirst}}</a>
			</h1>

		<!-- TIME AND PUBLISH -->
			<i class="bg-info timestamp">
			<span class="glyphicon glyphicon-time"></span> Published:
			<b>{{post.pub_date}}</b>, By: <span class="glyphicon glyphicon-user"></span> <b>{{post.author.name|capfirst}}</b></i>
			<p>{{post.content|safe|truncatewords_html:50}}</p>


			{% if post %}
				<a class="btn btn-primary" href="{{post.get_absolute_url}}">Read More</a>
			{% endif %}


			{% endfor %}

		{% else %}
			<h2> Sorry no posts related to tag : {{tag.name}}</h2>
		{% endif %}

	</div>
{% endblock %}

rubikPost/templates/rubikPost/post_detail.html
{% extends "base.html" %}

{% block title %}
	{{post|title}} - {{block.super}}
{% endblock %}

{% block banner %}

{% endblock %}

{% block content %}
	<div class="homePageContent">
		<p><<< <a href="#" onclick="goback()">Go Back</a></p>
		{% if post %}
		<!-- POST TITLE -->
		<h1 class="page-header">{{post.title}}</h1>

		<!-- TIME AND PUBLISH -->
			<i class="bg-info timestamp">
				<span class="glyphicon glyphicon-time"> Published: </span>
				<b>{{post.pub_date}}</b>, By: <span class="glyphicon glyphicon-user"></span> <b>{{post.author.name|capfirst}}</b></i>
		<br>
		<p class="postContent">{{post.content|safe|linebreaks}}</p>
		{% else %}
		<h2 class="bg-danger">Sorry Post was temporarily unavailabe or deleted</h2>
		{% endif %}
	</div>

{% endblock %}

{% block tags %}
	{% for tag in tags %}
		<span class="glyphicon glyphicon-tags">{{tag.name}}</span>
	{% endfor %}
{% endblock %}

rubikPost/templates/rubikPost/post_list.html
{% extends "base.html" %}
{% block content %}
	<h1 class="text-center">Recent Posts</h1>	
	{% for post in posts %}
		<div class="homePageContent">
			<!-- POST TITLE -->
			<h1>
				<a href="{{post.get_absolute_url}}">{{post.title|capfirst}}</a>
			</h1>

	<!-- TIME AND PUBLISH -->
		<i class="bg-info timestamp">
		<span class="glyphicon glyphicon-time"></span> Published:
		<b>{{post.pub_date}}</b>, By: <span class="glyphicon glyphicon-user"></span> <b>{{post.author.name|capfirst}}</b></i>

		<p class="post-content">{{post.content|safe|truncatewords_html:50}}</p>

		{% if post %}
			<a class="btn btn-primary" href="{{post.get_absolute_url}}">Read More</a>
		{% endif %}


		</div>
		<br /><hr />
	{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}HowToRubik{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="Rubiks cube,Cube,learn, rubik, howtorubik, magic cube, solve, cubing">
	<meta name="author" content="sashikanth">
	<meta name="HowToRubik" content="Ever thought to learn to solve a Rubik's cube and found no good tutorials? then you are in the right place where you can teach yourself how to solve it.">

	<link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">

  	{% load static %}
  	<link rel="shortcut icon" href="{% static 'rubikPost/img/favicon.ico' %}" type="image/x-icon">
	<link rel="stylesheet" type="text/css" href="{% static 'rubikPost/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'rubikPost/css/customStyles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'rubikPost/css/styles.css' %}">
	<script src="{% static 'rubikPost/js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'rubikPost/js/bootstrap.min.js' %}"></script>
</head>
<body>

	<div class="container-fluid mainDiv">

		{% include 'snippets/nav.html' %}

		{% block banner %}
		<div class="col-md-12 jumbotron jumbo" style="border-radius: 0px;">
			<div class="text-right">
				<h3>"<span class="textRed">If you are curious</span>, <span class="textBlue">you'll find cube around you..</span><br/>
				<span class="textGreen">If you are determined</span>, <span class="textYellow">you'll solve it..</span>"<br>~<span class="textWhite">Erno Rubik</span></h3>
			</div>
		</div>
		{% endblock %}

		<!-- End of container-fluid -->
	</div>
	<div class="container postContainer">
			<div class="row">
				<div class="col-md-9 homePageContentDiv">

				{% block content %}
				{% endblock %}

				<!-- End of col-9 -->
				</div>

				<div class="col-md-3">
					<div class="sideBoxes">
					<h1 class="page-header">Quick Look</h1>
						<div>
							<div class="tagBox">
							<P>TAGS:</P>
							{% for tag in tags %}
							<mark><a href="{% url 'post_by_tag' tag.slug %}"> {{tag.name}} </a></mark>&nbsp;
							{% endfor %}
							</div>
						</div>
					</div>
					<hr />
					<div class="sideBoxCubingMethods">
						<!-- <ul>
						<li>Basic Cubing</li>
						<li>Advanced Cubing</li>
						<li>...</li>
						</ul> -->
					</div>
				</div>
				<!-- End of row -->
			</div>
			<!-- End of container -->
	</div>
	<div class="container">
		<div id="disqus_thread"></div>
	</div>

	<script>

	/**
	*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
	*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
	/*
	var disqus_config = function () {
	this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	};
	*/
	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	s.src = 'https://howtorubik.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

	{% include "snippets/footer.html" %}
	<script>
		function goback() {
			window.history.back();
		}
	</script>
</body>
</html>

templates/snippets/footer.html
<!-- Footer -->
<footer class="page-footer blue center-on-small-only">
	<!-- Footer Links -->
	<div class="container-fluid">
		<div class="row">
			<!-- First Column -->
			<div class="col-md-6">
				<h4 class="title">Terms of use</h4>
				<p>This site is made with intention to provide simple understanding to solve the Rubik's cube and not to post any illegal content. All the content provided in these posts are meant for users and some of the resources are taken from the web to make things easier.</p>
			</div>
			<!-- /.End of First column -->

			<!-- Second Column -->
			<div class="col-md-6 secondFootCol">
				<h4 class="title">NAVIGATE</h4>
				<ul>
					<li><a href="{% url 'post_list' %}">Home</a></li>
					<li><a href="{% url 'about' %}">About</a></li>
					<li><a href="{% url 'contact' %}">Contact</a></li>
					<li><a href="{% url 'basicCubing' %}">Basic cubing</a></li>
					<li><a href="{% url 'advancedCubing' %}">Advanced cubing</a></li>
				</ul>
			</div>
			<!-- /. End of Second Column -->
		</div>
	</div>
	<!-- /.End of Footer Links -->

	<!-- Copy rights -->
	<div class="footer-copyright">
		<div class="container-fluid">
			&copy; Copy right <a href="https://www.howtorubik.herokuapp.com">howtorubik.com</a>
		</div>
	</div>
	<!-- /.End of Copy rights -->
</footer>
<!-- /. End of the Footer -->

templates/snippets/nav.html
<!-- NavBar- use .navbar, .navbar-default to get navbar, .container-fluid 
	for navbar to occupy full width of container  -->
<nav class="navbar navbar-inverse navbar-toggeleable">
	<div class="container">
		<!-- For logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>                        
		    </button>
		    {% load static %}
			<a href="{% url 'post_list' %}" class="navbar-brand" style="color:#ffffff"><img src="{% static 'rubikPost/img/rubiklogo.png' %}" class="img-responsive"></a>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'post_list' %}">
					<span class="glyphicon glyphicon-home"></span> Home
					</a>
				</li>
				<li><a href="{% url 'about' %}">About</a></li>
				<li><a href="{% url 'contact' %}">Contact</a></li>
				<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Start Cubing<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'basicCubing' %}">Basic 3x3</a></li>
						<!-- <li><a href="{% url 'advancedCubing' %}">Advance 3x3</a></li> -->
						<!-- <li><a href="">Basic 4x4</a></li>
						<li><a href="">Advance 4x4</a></li> -->
					</ul>
				</li>
				<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-facetime-video"></span> Video tutorials</a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'basicVideos' %}">Basic 3x3</a></li>
						<!-- <li><a href="{% url 'advancedVideos' %}">Advance 3x3</a></li> -->
					</ul>
				</li>
			</ul>
		</div>
	</div>
	
</nav>